thinframe.server:
    listen:
        port: 1337
        host: 127.0.0.1

twig:
    error_views:
        404: AcmeDemoApp:not_found.html.twig
        500: AcmeDemoApp:internal_server_error.html.twig

