parameters:

    karma.paths.root: .
    karma.paths.logs: '%karma.paths.root%/app/logs/'
    karma.paths.assets: '%karma.paths.root%/app/assets/'

    thinframe.server.port: 1337
    thinframe.server.host: '127.0.0.1'